baseurl = "https://jo3y49.github.io/"
defaultContentLanguage = "en-us"
languageCode = "en-us"
title = "Joseph May"
theme = "FeelIt"
canonifyURLs = true

[params]
    version = "1.0.X"
    description = "Joseph's Portfolio"
    keywords = ["Portfolio"]
    defaultTheme = "dark"
    author = "Joseph May"
    #info = "Game Developer"
    [params.pwa]
        # whether to enable PWA support
        enable = true
        # service-worker version
        version = "1.0.2"
    [params.header]
        # desktop header mode ("fixed", "normal", "auto")
        desktopMode = "fixed"
        # mobile header mode ("fixed", "normal", "auto")
        mobileMode = "auto"
        [params.header.title]
            # URL of the LOGO
            logo = ""
            # title name
            name = "Joseph May"
            # you can add extra information before the name (HTML format is supported), such as icons
            pre = ""
            # you can add extra information after the name (HTML format is supported), such as icons
            post = ""
    [params.footer]
        enable = true
        author = true
    
    [params.section]
        # special amount of posts in each section page
        paginate = 20
        # date format (month and day)
        #dateFormat = "01-02"
        # amount of RSS pages
        rss = 10
    
    [params.list]
        # special amount of posts in each list page
        paginate = 20
        # date format (month and day)
        #dateFormat = "01-02"
        # amount of RSS pages
        rss = 10

    [params.home]
        rss = 10
        # Home page profile
        [params.home.profile]
            enable = true
            # Gravatar Email for preferred avatar in home page
            gravatarEmail = ""
            # URL of avatar shown in home page
            #avatarURL = "/images/avatar.png"
            # title shown in home page (HTML format is supported)
            title = "Joey's Portfolio"
            # subtitle shown in home page
            subtitle = "Game Programmer"
            # whether to use typeit animation for subtitle
            typeit = false
            # whether to show social links
            social = true
            # disclaimer (HTML format is supported)
            disclaimer = ""
            # Header above the projects
            contentHeader = "Projects"
            # Home page posts
        [params.home.posts]
            enable = true
            # special amount of posts in each home posts page
            paginate = 6
            # display image-preview
            imagePreview = true
            # default behavior when you don't set "hiddenFromHomePage" in front matter
            defaultHiddenFromHomePage = false
    [params.social]
        GitHub = "jo3y49/"
        Linkedin = "joseph-may-1586a0221/"
        Itch = "jo3y49/"
    [params.page.toc]
        enable = false
    [params.page.comment]
        enable = false
    [params.about]
        enable = false

[menu]
  #[[menu.main]]
  #  identifier = "projects"
  #  # you can add extra information before the name (HTML format is supported), such as icons
  #  pre = ""
  #  # you can add extra information after the name (HTML format is supported), such as icons
  #  post = ""
  # name = "Projects"
  #  url = "/projects/"
  #  # title will be shown when you hover on this menu link
  #  title = ""
  #  weight = 1
  [[menu.main]]
    identifier = "resume"
    pre = ""
    post = ""
    name = "Resume"
    url = "/resume/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About Me"
    url = "/about/"
    title = ""
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/khusika/FeelIt/issues/158)
    noClasses = false
    [markup.goldmark]
[markup.goldmark.renderer]
    unsafe = true
